language: julia

julia:
  # - 1.5

os:
  - linux
  - osx

env:
- JULIA_PKG_SERVER="https://pkg.julialang.org"

notifications:
  email: true

before_script:
  - export PATH=$HOME/.local/bin:$PATH

branches:
  only:
    - master

stages:
  - name: test

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project -e 'using UUIDs; write("Project.toml", replace(read("Project.toml", String), r"uuid = .*?\n" =>"uuid = \"$(uuid4())\"\n"));'
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'
